{'runtime': datetime.datetime(2022, 3, 5, 17, 17, 2, 629518), 'exceptionDetails': 'No failed calls in this run.'}
{'runtime': datetime.datetime(2022, 3, 5, 17, 19, 9, 376615), 'exceptionDetails': 'No failed calls in this run.'}
{'runtime': datetime.datetime(2022, 3, 5, 17, 28, 20, 776708), 'exceptionDetails': [{'year': 2020, 'month': 1, 'failureReason': (<class 'ValueError'>, ValueError('Error 400: Invalid input'), <traceback object at 0x0000015FC8293240>)}]}
{'runtime': datetime.datetime(2022, 3, 5, 17, 29, 14, 309060), 'exceptionDetails': [{'year': 2020, 'month': 2, 'failureReason': (<class 'ValueError'>, ValueError('Error 400: Invalid input'), <traceback object at 0x0000024C37DA31C0>)}]}
{'runtime': datetime.datetime(2022, 3, 5, 17, 31, 19, 516218), 'exceptionDetails': [{'year': 2020, 'month': 2, 'failureReason': (<class 'ValueError'>, ValueError('Error 400: Invalid input'), <traceback object at 0x000001959B963180>)}, {'year': 2020, 'month': 3, 'failureReason': (<class 'ValueError'>, ValueError('Error 400: Invalid input'), <traceback object at 0x000001959B974D00>)}]}
{'runtime': datetime.datetime(2022, 3, 5, 17, 33, 11, 685089), 'exceptionDetails': 'No failed calls in this run.'}
{'runtime': datetime.datetime(2022, 3, 5, 17, 33, 58, 613163), 'exceptionDetails': 'No failed calls in this run.'}
{'runtime': datetime.datetime(2022, 3, 13, 13, 20, 29, 93991), 'exceptionDetails': [{'year': 2020, 'month': 1, 'failureReason': (<class 'ValueError'>, ValueError('Error 401: Invalid API Key'), <traceback object at 0x115bdbf40>)}, {'year': 2020, 'month': 2, 'failureReason': (<class 'ValueError'>, ValueError('Error 401: Invalid API Key'), <traceback object at 0x115be9c80>)}, {'year': 2020, 'month': 3, 'failureReason': (<class 'ValueError'>, ValueError('Error 401: Invalid API Key'), <traceback object at 0x115c0d740>)}, {'year': 2020, 'month': 4, 'failureReason': (<class 'ValueError'>, ValueError('Error 401: Invalid API Key'), <traceback object at 0x115c0e840>)}, {'year': 2020, 'month': 5, 'failureReason': (<class 'ValueError'>, ValueError('Error 401: Invalid API Key'), <traceback object at 0x115c14280>)}, {'year': 2020, 'month': 6, 'failureReason': (<class 'ValueError'>, ValueError('Error 401: Invalid API Key'), <traceback object at 0x115c15b80>)}, {'year': 2020, 'month': 7, 'failureReason': (<class 'ValueError'>, ValueError('Error 401: Invalid API Key'), <traceback object at 0x115c19e40>)}, {'year': 2020, 'month': 8, 'failureReason': (<class 'ValueError'>, ValueError('Error 401: Invalid API Key'), <traceback object at 0x115c20300>)}, {'year': 2020, 'month': 9, 'failureReason': (<class 'ValueError'>, ValueError('Error 401: Invalid API Key'), <traceback object at 0x115c23480>)}, {'year': 2020, 'month': 10, 'failureReason': (<class 'ValueError'>, ValueError('Error 401: Invalid API Key'), <traceback object at 0x115c25e80>)}, {'year': 2020, 'month': 11, 'failureReason': (<class 'ValueError'>, ValueError('Error 401: Invalid API Key'), <traceback object at 0x115c25c00>)}, {'year': 2020, 'month': 12, 'failureReason': (<class 'ValueError'>, ValueError('Error 401: Invalid API Key'), <traceback object at 0x115c0d4c0>)}]}
{'runtime': datetime.datetime(2022, 3, 13, 13, 21, 28, 934682), 'exceptionDetails': 'No failed calls in this run.'}
{'runtime': datetime.datetime(2022, 3, 13, 13, 25, 50, 73481), 'exceptionDetails': 'No failed calls in this run.'}
{'runtime': datetime.datetime(2022, 3, 13, 13, 30, 50, 49443), 'exceptionDetails': 'No failed calls in this run.'}
